### ISSUE TITLE
Any plans for Amazon RDS support?

### ISSUE THREAD

**Issue by seanrice** [unsignedapps/ua-aws-sdk-ios#1]
Hi Rob, any plans for Amazon RDS support?

**Comment by bok-** [comment]
Howdy! I can't promise anything overly stable, but I can add RDS support to the develop branch in a couple of hours and you can see how it looks.

**Comment by seanrice** [comment]
Really? it can't be that easy. for clarification, i'm used to pre-loading and fetching CoreData locally. now i'm looking at relational cloud-based services (we need secure multi-user access by teams) and data cached locally in CoreData for offline. The Amazon mobile SDK for iOS is almost perfect but lacks support for Amazon RDS.

**Comment by bok-** [comment]
Most of the code is generated from the web service definitions bundled in the PHP SDK. I merely convert that into Objective C. However, it depends on what you're trying to do. The RDS APIs themselves are just for _managing_ RDS instances. If you're trying to connect and retrieve data you would need a generic ODBC framework.

**Comment by seanrice** [comment]
Yes, connect and retrieve. Given status quo, i'm hoping to see an AWS-MySQL-RDS.framework added to the SDK soon. who wouldn't? =)

**Comment by bok-** [comment]
Unfortunately that is highly unlikely. There are already a number of common methods for connecting to a MySQL database from iOS apps. Unfortunately these involve using the official mysql libraries which are all C-based.

Generally it is not a great idea to do this anyway, as MySQL databases aren't the most secure things in the world - so it is always recommended they live behind a firewall and away from the Internet. The recommended approach is to write a web service and sit that in front of your databases.

If you don't want to run your own web services your other options might be to use a non-relational but mobile compatible database store like DynamoDB, or else using the AWS API Gateway + Lambda to emulate a web service and connect back to your MySQL instances that way.

Just to re-iterate, both this SDK and the official AWS SDKs are focused on providing a convenient wrapper for the AWS APIs - and in the case of RDS that only involves managing the DB instances, not acting as a database client. Your options there are generic MySQL or ODBC frameworks.

Sorry for the confusion.

**Comment by seanrice** [comment]
> Unfortunately that is highly unlikely. There are already a number of common methods for connecting to a MySQL database from iOS apps. Unfortunately these involve using the official mysql libraries which are all C-based.
> 
> Yes :) unfortunately.
> Generally it is not a great idea to do this anyway, as MySQL databases aren't the most secure things in the world - so it is always recommended they live behind a firewall and away from the Internet. The recommended approach is to write a web service and sit that in front of your databases.
> 
> If you don't want to run your own web services your other options might be to use a non-relational but mobile compatible database store like DynamoDB, or else using the AWS API Gateway + Lambda to emulate a web service and connect back to your MySQL instances that way.
> 
> That’s what they say :) but i figure a framework would handle all that… working with Cognito etc. Also, I looked at DynamoDB, would LOVE to use it, but fear being unable to perform database searches … and who knows what else? I’m working with a local relational database, am not sure what i’d run into.

API Gateway + Lambda … interesting. can’t hurt to look.

> Just to re-iterate, both this SDK and the official AWS SDKs are focused on providing a convenient wrapper for the AWS APIs - and in the case of RDS that only involves managing the DB instances, not acting as a database client. Your options there are generic MySQL or ODBC frameworks.
> 
> Thanks Rob. Would much prefer RDS framework that performs like Parse as a DB client. I think many developers would cheer and lots of creativity unleashed. See attached. This dude summed up my frustrations back in 2012 …
> 
> Sorry for the confusion.
> 
> No problemo! =)

Sean
